
/*
 * This file is autogenerated. Do not edit manually.
 */
#include <array>

#include "kernelj.hpp"
#include "fft.hpp"


ArrayJ FFT::fft(DeviceJ * device, ArrayJ * src, ArrayJ * dst)
{
    return ArrayJ{cle::fft::fft_func(device->get(), src->get(), dst == nullptr ? nullptr : dst->get())};
}

ArrayJ FFT::ifft(DeviceJ * device, ArrayJ * src, ArrayJ * dst)
{
    return ArrayJ{cle::fft::ifft_func(device->get(), src->get(), dst->get())};
}

ArrayJ FFT::convolve(DeviceJ * device, ArrayJ * src, ArrayJ * kernel, ArrayJ * dst, bool correlate)
{
    return ArrayJ{cle::fft::convolve_func(device->get(), src->get(), kernel->get(), dst == nullptr ? nullptr : dst->get(), correlate)};
}

ArrayJ FFT::deconvolve(DeviceJ * device, ArrayJ * src, ArrayJ * psf, ArrayJ * normalization, ArrayJ * dst, int iteration, float regularization)
{
    return ArrayJ{cle::fft::deconvolve_func(device->get(), src->get(), psf->get(), normalization == nullptr ? nullptr : normalization->get(), dst == nullptr ? nullptr : dst->get(), iteration, regularization)};
}

std::vector<int> FFT::smooth_shape(std::vector<int> shape)
{
    std::array<size_t, 3> shape_arr = {1, 1, 1};
    for (size_t i = 0; i < shape.size() && i < 3; ++i)
    {
        shape_arr[i] = static_cast<size_t>(shape[i]);
    }
    auto result = cle::fft::smooth_shape(shape_arr);
    return std::vector<int>(result.begin(), result.begin() + shape.size());
}

