/*
 * This file is autogenerated. Do not edit manually.
 */
#include "kernelj.hpp"
#include "transform.hpp"

ArrayJ Transform::affine_transform(DeviceJ * device, ArrayJ * src, ArrayJ * dst, AffineTransformJ * transform, bool interpolate, bool resize)
{
    (void)device;
    cle::transform::AffineTransform matrix = transform == nullptr ? cle::transform::AffineTransform() : transform->get();
    return ArrayJ{cle::transform::affine_transform(src->get(), dst == nullptr ? nullptr : dst->get(), matrix, interpolate, resize)};
}
