/**
 * This file is autogenerated. Do not edit manually.
 */    
package net.clesperanto.kernels;

import java.util.Objects;
import java.util.ArrayList;

import net.clesperanto.core.ArrayJ;
import net.clesperanto.core.DeviceJ;
import net.clesperanto.core.Utils;

/**
 * Class containing all FFT related functions
 */
public class FFT {

	/**
	 * Performs a 1D, 2D, or 3D FFT (Fast Fourier Transform) on the input image.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ fft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.FFT.fft(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw()));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D IFFT (Inverse Fast Fourier Transform) on the input image.
	 * The input image must be Hermitian, and the output image must be provided as the second argument.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image.
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ ifft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(output, "output cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.FFT.ifft(device.getRaw(), input.getRaw(), output.getRaw()));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D convolution using FFT between an input image and a kernel.
	 * Input image, PSF kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and PSF kernel to the same size as the closest smooth size and will take care of the PSF kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param kernel ({@link ArrayJ}) - Kernel image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param correlate (boolean) - If true, convolution with the PSF reversed. (default: False)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ convolve(DeviceJ device, ArrayJ input, ArrayJ kernel, ArrayJ output, boolean correlate) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(kernel, "kernel cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.FFT.convolve(device.getRaw(), input.getRaw(), kernel.getRaw(), output == null ? null : output.getRaw(), correlate));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D deconvolution using FFT between an input image and a PSF kernel.
	 * The deconvolution is performed using the Richardson-Lucy algorithm and requires a maximum iteration number.
	 * The user can specify a normalization image (optional) and a regularization parameter (optional) to apply Total Variation regularization.
	 * Input image, PSF kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and PSF kernel to the same size as the closest smooth size and will take care of the PSF kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param psf ({@link ArrayJ}) - Kernel image.
	 * @param normalization ({@link ArrayJ}) - Normalization image. (default: None)
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param iteration (int) - Maximum number of iterations. (default: 100)
	 * @param regularization (float) - Regularization parameter. (default: 0.0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ deconvolve(DeviceJ device, ArrayJ input, ArrayJ psf, ArrayJ normalization, ArrayJ output, int iteration, float regularization) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(psf, "psf cannot be null");
		Objects.requireNonNull(normalization, "normalization cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.FFT.deconvolve(device.getRaw(), input.getRaw(), psf.getRaw(), normalization == null ? null : normalization.getRaw(), output == null ? null : output.getRaw(), iteration, regularization));
    }
    
	/**
	 * Get the closest smooth shape from a given input shape, to insure efficient fft operations.
	 * @param shape (ArrayList&amp;lt;Integer&amp;gt;) - Input shape.
	 * @return ArrayList&amp;lt;Integer&amp;gt;
	 * @throws NullPointerException if the shape parameter is null.
	 */
    public static ArrayList<Integer> smoothShape(ArrayList<Integer> shape) {
        Objects.requireNonNull(shape, "shape cannot be null");
        return Utils.toArrayList(net.clesperanto._internals.kernelj.FFT.smooth_shape(Utils.toIntVector(shape)));
    }
    
}
