
/**
 * This file is autogenerated. Do not edit manually.
 */    
package net.clesperanto.kernels;

import java.util.Objects;
import java.util.ArrayList;
import java.util.HashMap;

import net.clesperanto.core.ArrayJ;
import net.clesperanto.core.DeviceJ;
import net.clesperanto.core.Utils;

/**
 * Class containing all functions of tier 8 category
 */
public class Tier8 {

	/**
	 * Applies a morphological opening operation to a label image and afterward   fills gaps between the labels using Voronoi labeling.
	 * Finally, the result   label image is masked so that all background pixels remain background pixels.
	 * Note: It is recommended to process isotropic label images.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input label image.
	 * @param output ({@link ArrayJ}) - Output label image. (default: None)
	 * @param radius (int) - Smoothing radius. (default: 0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ smoothLabels(DeviceJ device, ArrayJ input, ArrayJ output, int radius) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.smooth_labels(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), radius));
    }
    
	/**
	 * Applies a morphological erosion and dilation of the label image with respect to     the connectivity of the labels.
	 * Note: It is recommended to process isotropic label images.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input label image.
	 * @param output ({@link ArrayJ}) - Output label image. (default: None)
	 * @param radius (int) - Smoothing radius. (default: 0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ smoothConnectedLabels(DeviceJ device, ArrayJ input, ArrayJ output, int radius) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.smooth_connected_labels(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), radius));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D FFT (Fast Fourier Transform) on the input image.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ fft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.fft(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw()));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D IFFT (Inverse Fast Fourier Transform) on the input image.
	 * The input image must be Hermitian, and the output image must be provided as the second argument.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image.
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ ifft(DeviceJ device, ArrayJ input, ArrayJ output) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(output, "output cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.ifft(device.getRaw(), input.getRaw(), output.getRaw()));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D convolution using FFT between an input image and a kernel.
	 * Input image, PSF kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and PSF kernel to the same size as the closest smooth size and will take care of the PSF kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param kernel ({@link ArrayJ}) - Kernel image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param correlate (boolean) - If true, convolution with the PSF reversed. (default: False)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ convolveFft(DeviceJ device, ArrayJ input, ArrayJ kernel, ArrayJ output, boolean correlate) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(kernel, "kernel cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.convolve_fft(device.getRaw(), input.getRaw(), kernel.getRaw(), output == null ? null : output.getRaw(), correlate));
    }
    
	/**
	 * Performs a 1D, 2D, or 3D deconvolution using FFT between an input image and a PSF kernel.
	 * The deconvolution is performed using the Richardson-Lucy algorithm and requires a maximum iteration number.
	 * The user can specify a normalization image (optional) and a regularization parameter (optional) to apply Total Variation regularization.
	 * Input image, PSF kernel, and normalization image are expected to be in the spatial domain.
	 * The function will automatically pad the input image and PSF kernel to the same size as the closest smooth size and will take care of the PSF kernel centering.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param psf ({@link ArrayJ}) - Kernel image.
	 * @param normalization ({@link ArrayJ}) - Normalization image. (default: None)
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param iteration (int) - Maximum number of iterations. (default: 100)
	 * @param regularization (float) - Regularization parameter. (default: 0.0)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ deconvolveFft(DeviceJ device, ArrayJ input, ArrayJ psf, ArrayJ normalization, ArrayJ output, int iteration, float regularization) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
		Objects.requireNonNull(psf, "psf cannot be null");
		Objects.requireNonNull(normalization, "normalization cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.deconvolve_fft(device.getRaw(), input.getRaw(), psf.getRaw(), normalization == null ? null : normalization.getRaw(), output == null ? null : output.getRaw(), iteration, regularization));
    }
    
	/**
	 * Resamples an image to make it isotropic by rescaling the image to a target spacing.
	 * The current spacings of the image in x, y, and z dimensions must be provided and should be &amp;gt;= 0.
	 * If the target spacing is &amp;lt;= 0 or not provided, the function assumes the target spacing is the minimum of the current spacings.
	 * Finally, an interpolation option is provided to choose whether to interpolate the image during rescaling or not (default is true).
	 * For label images, it is recommended to set the interpolation option to false.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param current_spacing_x (float) - Original spacing in x dimension. (default: 1.0)
	 * @param current_spacing_y (float) - Original spacing in y dimension. (default: 1.0)
	 * @param current_spacing_z (float) - Original spacing in z dimension. (default: 1.0)
	 * @param target_spacing (float) - Target isotropic spacing. (default: -1.0)
	 * @param interpolate (boolean) - If true, interpolate the image during rescaling. (default: True)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ makeIsotropic(DeviceJ device, ArrayJ input, ArrayJ output, float current_spacing_x, float current_spacing_y, float current_spacing_z, float target_spacing, boolean interpolate) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.make_isotropic(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), current_spacing_x, current_spacing_y, current_spacing_z, target_spacing, interpolate));
    }
    
	/**
	 * Resamples an image to make it anisotropic by rescaling the image to target spacings in x, y, and z dimensions.
	 * The current isotropic spacing of the image in each dimension must be provided and should be &amp;gt;= 0.
	 * If the target spacings for x, y, and z shoudl be provided and &amp;gt;= 0.
	 * Finally, an interpolation option is provided to choose whether to interpolate the image during rescaling or not (default is true).
	 * For label images, it is recommended to set the interpolation option to false.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param current_spacing (float) - Current spacing of the image in each dimension. (default: -1.0)
	 * @param target_spacing_x (float) - Target spacing in x dimension. (default: -1.0)
	 * @param target_spacing_y (float) - Target spacing in y dimension. (default: -1.0)
	 * @param target_spacing_z (float) - Target spacing in z dimension. (default: -1.0)
	 * @param interpolate (boolean) - If true, interpolate the image during rescaling. (default: True)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ makeAnisotropic(DeviceJ device, ArrayJ input, ArrayJ output, float current_spacing, float target_spacing_x, float target_spacing_y, float target_spacing_z, boolean interpolate) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Tier8.make_anisotropic(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), current_spacing, target_spacing_x, target_spacing_y, target_spacing_z, interpolate));
    }
    
}
