/**
 * This file is autogenerated. Do not edit manually.
 */    
package net.clesperanto.kernels;

import java.util.Objects;

import net.clesperanto.core.AffineTransform;
import net.clesperanto.core.ArrayJ;
import net.clesperanto.core.DeviceJ;

/**
 * Class containing all geometric transform related functions
 */
public class Transform {

	/**
	 * Applies an affine transformation matrix to an array and returns the result.
	 * If no transform is given, the identity matrix will be used.
	 * @param device ({@link DeviceJ}) - Device to perform the operation on.
	 * @param input ({@link ArrayJ}) - Input image to be transformed.
	 * @param output ({@link ArrayJ}) - Output image. (default: None)
	 * @param transform ({@link AffineTransform}) - Affine transformation matrix. (default: None)
	 * @param interpolate (boolean) - If true, bi/trilinear interpolation will be applied, if hardware allows. (default: False)
	 * @param resize (boolean) - Automatically determines the size of the output depending on the transformation. (default: False)
	 * @return {@link ArrayJ}
	 * @throws NullPointerException if any of the device or input parameters are null.
	 */
    public static ArrayJ affineTransform(DeviceJ device, ArrayJ input, ArrayJ output, AffineTransform transform, boolean interpolate, boolean resize) {
        Objects.requireNonNull(device, "device cannot be null");
		Objects.requireNonNull(input, "input cannot be null");
        return new ArrayJ(net.clesperanto._internals.kernelj.Transform.affine_transform(device.getRaw(), input.getRaw(), output == null ? null : output.getRaw(), transform == null ? null : transform.getRaw(), interpolate, resize));
    }
    
}
